### ISSUE TITLE
Unable to build in Windows (MSYS2)

### ISSUE THREAD

**Issue by spoiledsport** [lkl/linux#260] opened 2016-11-07 20:16 UTC
After following the setup instruction for windows, I am unable to build. The build is failing with the following error

make: Entering directory '/e/dev/GitHub/LKL/linux/tools/lkl'
Makefile:77: *** Unrecognized platform: pe-x86-64.  Stop.
make: Leaving directory '/e/dev/GitHub/LKL/linux/tools/lkl'

Any clues?

**Comment by Rondom** [comment] 2016-11-07 22:07
Build for 32-bit (easiest by using the "MINGW32" shell). See #25

**Comment by tavip** [comment] 2016-11-18 12:59
Duplicate of #25, closing this issue.

**Closed by tavip** 2016-11-18 12:59 UTC
