### ISSUE TITLE
Run two instances of LKL in a same process

### ISSUE THREAD

**Issue by stfairy** [lkl/linux#51] opened 2016-01-28 20:42 UTC
It seems impossible at the moment to run two instances of LKL (e.g. two separate calls to `lkl_start_kernel` etc.) in a same process.  Any idea how to do that easily?

**Comment by opurdila** [comment] 2016-01-29 00:00
I think that is caused by global variables (in both the LKL code and the core kernel code). I am not sure if we can fix that. 

What use case do you have in mind for this, maybe we can use an alternate approach?

**Comment by stfairy** [comment] 2016-01-29 00:09
My immediate use case is to run two LKL side by side in two threads of a single process, and exchange packets between them without host kernel intervention.

In the long run, I think it might be good if users can have an arbitrary number of instances, since LKL is a "library".

**Comment by thehajime** [comment] 2016-01-29 00:29
We're using ```dlmopen(3)``` (not dlopen(3)) in the ns-3 simulator integration to host multiple instances of libos kernel (not LKL's one).

related code is [available](https://github.com/direct-code-execution/ns-3-dce/blob/master/model/dlm-loader-factory.cc#L93) though I don't see an immediate answer for the usecase with LKL.

@stfairy, in your usecase, are you running multiple (virtual) hosts in a single process and exchange data between them by memory reference ? if this is the case, the above example might be helpful.

**Comment by stfairy** [comment] 2016-01-29 02:24
@thehajime Yes, thanks for the pointer.  I'll take a look.

**Comment by liuyuan10** [comment] 2016-11-03 03:05
I tried to use dlmopen to have multiple LKL instance in one process. I found the tls doesn't work with dlmopen. I wrote a simple program to prove it:
https://raw.githubusercontent.com/liuyuan10/linux/5bf7ebe0a7c6e3a695148b749b147c2de81d3c26/tools/lkl/tests/test-tls.c

To run:
cd tools/lkl
gcc test-tls.c -ldl -Iinclude
./a.out

Output:
num = 0
tls_alloc key = 0
tls_get value = 0
tls_get value = 1000
num = 1
tls_alloc key = 0
tls_get value = 1000
tls_get value = 1001

So it means the 2nd tls alloc doesn't create a new tls at all so the 2nd LKL syscall will fail. I'm not able to find any clue searching the internet.

Disabling tls ops is not an option where only one syscall is allowed at a time. I'll use a thread-safe map to simulate tls if I can't get around this issue.

**Comment by stfairy** [comment] 2016-11-04 04:45
I debugged this before, and there was a bunch of TODOs regarding TLS in the glibc code base.  I might have written down my findings somewhere (e.g. snippets).

**Comment by thehajime** [comment] 2016-11-04 05:17
I played a bit with @liuyuan10's test code and confirmed the bug (I'm with glibc 2.23.1-10 of fedora 24).

We had our own loader instead of glibc which reimplements dlmopen etc for our use (of ns-3).  Our original motivation was to avoid the hard limit of the number of instances with glibc (i.e., 16, `# define DL_NNS 16`).

http://code.nsnam.org/mathieu/elf-loader/
http://code.nsnam.org/thehajime/elf-loader/ (fork of the above)

I will find some time to check with the elf-loader and your test code.

**Comment by liuyuan10** [comment] 2016-11-28 18:47
An update on this issue. I gave up dlmopen and successfully runs many LKL instances in a process by renaming liblkl.so. Issues with dlmopen are
* tls_alloc in two different namespace don't create different keys as described above
* Has to load librt/libc in each namespace and hit the limitation of number of static TLS.
* lkl_start_kernel in different thread crashes

I'm closing this issue given there is a solution to make it work.

**Closed by liuyuan10** 2016-11-28 18:47 UTC

**Comment by thehajime** [comment] 2016-11-29 13:35
@liuyuan10 great to hear that.

it would be great if you could share your multi-lkl application as an example (or test code) for the future reference.

**Comment by liuyuan10** [comment] 2016-11-29 20:50
tests/multi_lkl.c
`#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <lkl.h>
#include <lkl_host.h>

#define NUM_LKL 50
const char TMP_DIR[] = "/tmp";

void * get_sym(void *lib, const char* sym) {
	void *addr = dlsym(lib, sym);
	char *error = dlerror();
	if (error != NULL) {
		fprintf(stderr, "get_sym: %s\n", error);
		exit(EXIT_FAILURE);
	}
	return addr;
}

typedef int (*lkl_start_kernel_t)(struct lkl_host_operations* lkl_ops,
				  unsigned long mem_size,
				  const char* cmd_line, ...);
typedef long (*lkl_syscall_t)(long no, long* params);
typedef long (*lkl_sys_halt_t)(void);

void *do_stuff(void *arg) {
	unsigned long id = (unsigned long) arg;
	int err;
	char liblkl[50];

	sprintf(liblkl, "%s/liblkl-%lu.so", TMP_DIR, id);
	void *lkl = dlopen(liblkl, RTLD_NOW);
	if (!lkl) {
		fprintf(stderr, "dlopen: %s\n", dlerror());
		exit(EXIT_FAILURE);
	}
	struct lkl_host_operations* lkl_ops = get_sym(lkl, "lkl_host_ops");
	lkl_start_kernel_t start_lkl = get_sym(lkl, "lkl_start_kernel");
	lkl_syscall_t lkl_syscall = get_sym(lkl, "lkl_syscall");
	lkl_sys_halt_t stop_lkl = get_sym(lkl, "lkl_sys_halt");

	err = start_lkl(lkl_ops, 16 * 1024 * 1024, "");
	if (err) {
		fprintf(stderr, "lkl_start_kernel failed\n");
		exit(EXIT_FAILURE);
	}

	long params[6];
	lkl_syscall(__lkl__NR_getpid, params);

	stop_lkl();
	/* Wait a while for the zombie timers */
	sleep(1);
	dlclose(lkl);
	return NULL;
}

int main(int argc, char **argv) {
	unsigned long i;
	pthread_t threads[NUM_LKL];
	char liblkl_paths[NUM_LKL * 50] = "";
	for(i = 0; i < NUM_LKL; ++i) {
		char tmp[50];
		sprintf(tmp, " %s/liblkl-%lu.so", TMP_DIR, i);
		strcat(liblkl_paths, tmp);
	}

	char cmd[NUM_LKL * 50 + 100];
	sprintf(cmd, "echo %s | xargs -n 1 cp liblkl.so", liblkl_paths);
	system(cmd);

	for (i = 0; i < NUM_LKL; i++) {
		if (pthread_create(&threads[i], NULL, do_stuff, (void*)i)) {
			fprintf(stderr, "pthread_create: :-(\n");
			return 1;
		}
	}

	for (i = 0; i < NUM_LKL; i++) {
		if (pthread_join(threads[i], NULL)) {
			fprintf(stderr, "pthread_join: :(\n");
		}
	}


	sprintf(cmd, "rm %s", liblkl_paths);
	system(cmd);
	return 0;
}
`
cd tools/lkl
gcc  -Iinclude  tests/multi_lkl.c   -ldl -lpthread
./a.out
