### ISSUE TITLE
LKL uses 100% CPU after adding a network device

### ISSUE THREAD

**Issue by tommie-lie** [lkl/linux#140] opened 2016-03-30 16:51 UTC
I'm slightly puzzled by the fact that nobody else has already seen this issue which was introduced by 1f5a1affc6bd793f87a1bb13d41adaf7dd089eb9.

The semaphore `virtio_net_poll.sem` which served the purpose of blocking the poll thread while there really was nothing to do, was removed in the mentioned commit.
As a result, the poll thread that handles the tx queue issues a `poll()` call on the data stream descriptor (a tap device in case of virtio_net_tap) which immediately returns 99.9% of the time. If the tx queue is empty, `virtio_process_queue()` also returns immediately. As there is nothing else the loop does, it becomes a busy waiting loop and uses up one complete CPU core.

Steps to reproduce:
Build current lkl master. Add `$(hijack_script} sleep 300` to `tools/lkl/tests/hijack-test.sh` in line 76 (after the LKL_HIJACK exports and the tap device initialization). Run `make test` and watch your htop for a sleep process.

Partly reverting 1f5a1affc6bd793f87a1bb13d41adaf7dd089eb9 to restore the semaphore just caused another problem with the new eventfd closing mechanism: There is no way from `net_close()` in `virtio_net_tap.c` to access the poll queue data structure and increment the semaphore and `net_close()` is designed to be blocking until the threads joins.

If someone has a bright idea how to solve this elegantly, it'd be very welcome. I'll investigate further.

**Comment by pscollins** [comment] 2016-03-30 17:04
The semaphore wasn't doing its job correctly because when `virtio_net_enqueue` is called from an interrupt handler, it is `sem_up`'d without a corresponding `sem_down` (because it didn't pass through `net_poll`). So after an interrupt handler fires once, the TX thread never sleeps again --- the semaphore holds a bigger and bigger value over the lifetime of the program. I'm not sure if re-adding that semaphore will fix it because I don't know if it's safe for an interrupt hander thread to sleep on a host semaphore.

**Comment by tommie-lie** [comment] 2016-03-30 17:32
I'm sorry if I left the impression that your commit should be completely reverted, I'm sure it was necessary and the semaphore did behave strangely before.

Just adding the semaphore to the tx poll thread definitely is enough, the rx thread behaves normally. There still the problem with the eventfd, though. I'm not convinced exposing `net_poll` to `lkl_netdev` is the nice thing to do. `net_poll` seems more like an implementation detail to me instead of an interface.

**Comment by pscollins** [comment] 2016-03-30 18:03
Not at all! I didn't realize that was there for performance, I was very puzzled why it seemed to be acquiring a lock after the critical section was over.  I removed it because I thought it was intended to do synchronization that was now being handled differently. 

If you don't want to expose the struct members, it might be enough to add some functions like `lkl_netdev_rx_wake` that `sem_up` the semaphore in the RX `net_poll`. 

If I remember correctly how the code used to work, though, I couldn't figure out how a thread would ever end up sleeping on it. Can I talk through it with you? Correct me when I'm wrong, here's how I thought it worked in the TX thread case:

1. `dev->tx_poll.sem` is initialized to 0
2. The TX poll thread enters `poll_thread`
3. `np->dev->ops->poll` polls the TAP fd looking for `POLLOUT`
4. A write won't block right now because nothing is on the fd, so it returns 1 immediately and sets `LKL_DEV_NET_POLL_TX`
5. The second condition in `poll_thread` fires and the TX poll thread enters `virtio_process_queue` and eventually ends up in `net_enqueue` 
6. It hits the `is_tx_queue` case and tries to write `len` bytes to the fd
7. `len == 0` because we never had anything to write, so `net_tx` immediately returns -1
8. The TX poll thread calls on `sem_up(dev->tx_poll.sem)` and its value is now 1
9. We eventually get back up to `poll_thread` and call `sem_down(dev->tx_poll.sem)`; its value is now 0
10. goto 3

What's the case that results in the TX thread sleeping? Or have I missed something here?

**Comment by tommie-lie** [comment] 2016-03-30 20:28
You are partly right and I was partly wrong. I misread the `ret < 0` as `ret > 0` and drew my conclusions from the behaviour I observed. You are right except for steps 7 and 8 which never happen like this.
What happens instead is that the first time `virtio_process_queue` is called, the queue is not ready (`q->ready` is false) and the function returns immediately without calling `net_enqueue`. Then the semaphore is `sem_down`ed and the tx thread sleeps forever as long as there are no large or interrupted writes. In fact, the whole network stuff still works if I completely disable the tx poll thread.

**Comment by pscollins** [comment] 2016-03-30 20:34
Wow, that's a really interesting find. What did you do to test the networking stuff --- just `make test`? I have no idea how TX packets could be making it to the host if not on the TX poll thread. Maybe an interrupt is doing the work?

**Comment by tommie-lie** [comment] 2016-03-30 20:49
Yeah, I can reproduce everything with a very long sleep mentioned in the first comment. Starting from that, I can issue pings from the host and watch them being answered (albeit after 9 packets got lost (reproducibly!) probably due to all my fiddling around so far).
The packets are really sent by `virtio_write()` which directly calls `virtio_process_queue()`. `virtio_write` is ultimately directly called from the kernel code. Only if the write would block, the tx thread takes over. However, I still can't wrap my head around the "queue" mechanism for requests. I would probably have to read a bit about the virtio interface workings.

It seems to me like some of the code seems to be merely working by accident and is overly complicated ;-)
There probably should only be a single point of entrance for `net_tx` and I think this should be the separate thread. If the kernel decides it has stuff to send, it should wake up the thread rather than calling `net_enqueue`. Or are there any guarantees about sending the data from the kernel's point of view that would require sending the data directly from the virtio hook?

**Comment by pscollins** [comment] 2016-03-30 21:24
I think the kernel interface is the more important one here --- the real work is done inside drivers/virtio. I'd guess that `virtio_write` is called in an interrupt handler of some sort.

> albeit after 9 packets got lost (reproducibly!) probably due to all my fiddling around so far

I've seen that before, I think it had something to do with the time it took for the route to get resolved --- you can confirm that's the problem if you set the MAC address to be the same each run and the problem goes away. (No idea what's really happening there, though). 

>  I would probably have to read a bit about the virtio interface workings.

There's some very good example code with comments about the spec in `lguest` (a toy hypervisor in the Linux kernel tree, iirc `arch/lguest`), which was written by Rusty Russel (who created virtio). He also wrote a [paper](ftp://ftp.os3.nl/people/nsijm/INR/Week%201/papers/32_virtio_Russel.pdf) about the original design which I found very helpful.

> If the kernel decides it has stuff to send, it should wake up the thread rather than calling net_enqueue. Or are there any guarantees about sending the data from the kernel's point of view that would require sending the data directly from the virtio hook?

I'm not sure. There is some stuff where the virtio drivers trigger interrupts that must act a certain way, but I don't remember how that is. I think simplifying the virtio stuff would be fantastic; it has been a major source of pain. Some things to be aware of are:

* it's tricky to synchronize host-scheduled threads and LKL threads since it's dangerous to hold host locks in LKL threads --- a lot of strangeness in the codebase exists to work around that, maybe it was a factor here

* there are now a number of implementations other than tap that hook into the `net_poll` stuff --- maybe one of them has a dependency on that TX poll thread that doesn't exist in tap

**Comment by tommie-lie** [comment] 2016-03-31 14:38
Thanks for the pointer to lguest and Rusty Russell's paper. From those two I don't think there are any requirements to the I/O processing that the guest kernel can make. From what I see in lguest it should be fine to have a single thread that does the writing. The virtio notify does what the name suggests: notifies an eventfd, whereas in LKL it calls `net_enqueue()` directly.

In the end, poll_thread for the tx thread should wait for an event (either via a semaphore or an eventfd) and `virtio_write()` should notify this event so that the thread can process the new data.
I'm not sure if I can find the time to implement that myself soon (there are too many other loose ends at $workplace), but I will try.

**Comment by liuyuan10** [comment] 2016-03-31 17:06
Just want to bring up another point. Is it easier to temporarily fix it by using epoll (event triggered) on tx event? So the tx polling thread will only be unblocked when someone fill up the buffer. And net close should work completely as it is and not much change is needed.

I can draft a PR if you think it's doable.

**Comment by pscollins** [comment] 2016-03-31 17:13
SGTM

**Comment by liuyuan10** [comment] 2016-04-15 16:43
The 100% CPU issue is already fixed by PR #143 . However, having eventfd between driver and device to wake up polling threads are still better, in which way no lock is needed around the queues.

@tommie-lie Are you planning to do this? I'd like to help in any way.

**Comment by opurdila** [comment] 2016-08-19 00:05
I think this issue is fixed, please reopen if I am wrong.

**Closed by opurdila** 2016-08-19 00:05 UTC
